'use strict';

var React = require('react-native');

var {
  ListView,
  StyleSheet,
  View,
  Text,
  Image,
  TouchableHighlight,
  TouchableOpacity,
  StatusBarIOS
} = React;

var RepoRow = require('./RepoRow');

var FAKE_DATA = [
  {
    "id": 36861678,
    "name": "FontAwesomeKit",
    "full_name": "skyline75489/FontAwesomeKit",
    "owner": {
      "login": "skyline75489",
      "id": 4710575,
      "avatar_url": "https://avatars.githubusercontent.com/u/4710575?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skyline75489",
      "html_url": "https://github.com/skyline75489",
      "followers_url": "https://api.github.com/users/skyline75489/followers",
      "following_url": "https://api.github.com/users/skyline75489/following{/other_user}",
      "gists_url": "https://api.github.com/users/skyline75489/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skyline75489/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skyline75489/subscriptions",
      "organizations_url": "https://api.github.com/users/skyline75489/orgs",
      "repos_url": "https://api.github.com/users/skyline75489/repos",
      "events_url": "https://api.github.com/users/skyline75489/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skyline75489/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/skyline75489/FontAwesomeKit",
    "description": "Icon font library for iOS. Currently supports Font-Awesome, Foundation icons, Zocial, and ionicons.",
    "fork": true,
    "url": "https://api.github.com/repos/skyline75489/FontAwesomeKit",
    "forks_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/forks",
    "keys_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/teams",
    "hooks_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/hooks",
    "issue_events_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/issues/events{/number}",
    "events_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/events",
    "assignees_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/assignees{/user}",
    "branches_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/branches{/branch}",
    "tags_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/tags",
    "blobs_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/languages",
    "stargazers_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/stargazers",
    "contributors_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/contributors",
    "subscribers_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/subscribers",
    "subscription_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/subscription",
    "commits_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/contents/{+path}",
    "compare_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/merges",
    "archive_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/downloads",
    "issues_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/issues{/number}",
    "pulls_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/labels{/name}",
    "releases_url": "https://api.github.com/repos/skyline75489/FontAwesomeKit/releases{/id}",
    "created_at": "2015-06-04T09:41:38Z",
    "updated_at": "2015-06-04T09:41:39Z",
    "pushed_at": "2015-06-04T11:13:29Z",
    "git_url": "git://github.com/skyline75489/FontAwesomeKit.git",
    "ssh_url": "git@github.com:skyline75489/FontAwesomeKit.git",
    "clone_url": "https://github.com/skyline75489/FontAwesomeKit.git",
    "svn_url": "https://github.com/skyline75489/FontAwesomeKit",
    "homepage": "",
    "size": 2064,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Objective-C",
    "has_issues": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 30512497,
    "name": "python-playground",
    "full_name": "skyline75489/python-playground",
    "owner": {
      "login": "skyline75489",
      "id": 4710575,
      "avatar_url": "https://avatars.githubusercontent.com/u/4710575?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skyline75489",
      "html_url": "https://github.com/skyline75489",
      "followers_url": "https://api.github.com/users/skyline75489/followers",
      "following_url": "https://api.github.com/users/skyline75489/following{/other_user}",
      "gists_url": "https://api.github.com/users/skyline75489/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skyline75489/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skyline75489/subscriptions",
      "organizations_url": "https://api.github.com/users/skyline75489/orgs",
      "repos_url": "https://api.github.com/users/skyline75489/repos",
      "events_url": "https://api.github.com/users/skyline75489/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skyline75489/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/skyline75489/python-playground",
    "description": "my python playground",
    "fork": false,
    "url": "https://api.github.com/repos/skyline75489/python-playground",
    "forks_url": "https://api.github.com/repos/skyline75489/python-playground/forks",
    "keys_url": "https://api.github.com/repos/skyline75489/python-playground/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/skyline75489/python-playground/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/skyline75489/python-playground/teams",
    "hooks_url": "https://api.github.com/repos/skyline75489/python-playground/hooks",
    "issue_events_url": "https://api.github.com/repos/skyline75489/python-playground/issues/events{/number}",
    "events_url": "https://api.github.com/repos/skyline75489/python-playground/events",
    "assignees_url": "https://api.github.com/repos/skyline75489/python-playground/assignees{/user}",
    "branches_url": "https://api.github.com/repos/skyline75489/python-playground/branches{/branch}",
    "tags_url": "https://api.github.com/repos/skyline75489/python-playground/tags",
    "blobs_url": "https://api.github.com/repos/skyline75489/python-playground/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/skyline75489/python-playground/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/skyline75489/python-playground/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/skyline75489/python-playground/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/skyline75489/python-playground/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/skyline75489/python-playground/languages",
    "stargazers_url": "https://api.github.com/repos/skyline75489/python-playground/stargazers",
    "contributors_url": "https://api.github.com/repos/skyline75489/python-playground/contributors",
    "subscribers_url": "https://api.github.com/repos/skyline75489/python-playground/subscribers",
    "subscription_url": "https://api.github.com/repos/skyline75489/python-playground/subscription",
    "commits_url": "https://api.github.com/repos/skyline75489/python-playground/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/skyline75489/python-playground/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/skyline75489/python-playground/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/skyline75489/python-playground/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/skyline75489/python-playground/contents/{+path}",
    "compare_url": "https://api.github.com/repos/skyline75489/python-playground/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/skyline75489/python-playground/merges",
    "archive_url": "https://api.github.com/repos/skyline75489/python-playground/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/skyline75489/python-playground/downloads",
    "issues_url": "https://api.github.com/repos/skyline75489/python-playground/issues{/number}",
    "pulls_url": "https://api.github.com/repos/skyline75489/python-playground/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/skyline75489/python-playground/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/skyline75489/python-playground/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/skyline75489/python-playground/labels{/name}",
    "releases_url": "https://api.github.com/repos/skyline75489/python-playground/releases{/id}",
    "created_at": "2015-02-09T01:07:55Z",
    "updated_at": "2015-05-06T01:05:32Z",
    "pushed_at": "2015-06-03T08:25:53Z",
    "git_url": "git://github.com/skyline75489/python-playground.git",
    "ssh_url": "git@github.com:skyline75489/python-playground.git",
    "clone_url": "https://github.com/skyline75489/python-playground.git",
    "svn_url": "https://github.com/skyline75489/python-playground",
    "homepage": null,
    "size": 284,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Python",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 29445122,
    "name": "what-happens-when-zh_CN",
    "full_name": "skyline75489/what-happens-when-zh_CN",
    "owner": {
      "login": "skyline75489",
      "id": 4710575,
      "avatar_url": "https://avatars.githubusercontent.com/u/4710575?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skyline75489",
      "html_url": "https://github.com/skyline75489",
      "followers_url": "https://api.github.com/users/skyline75489/followers",
      "following_url": "https://api.github.com/users/skyline75489/following{/other_user}",
      "gists_url": "https://api.github.com/users/skyline75489/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skyline75489/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skyline75489/subscriptions",
      "organizations_url": "https://api.github.com/users/skyline75489/orgs",
      "repos_url": "https://api.github.com/users/skyline75489/repos",
      "events_url": "https://api.github.com/users/skyline75489/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skyline75489/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/skyline75489/what-happens-when-zh_CN",
    "description": "What-happens-when 的中文翻译，原仓库 https://github.com/alex/what-happens-when",
    "fork": false,
    "url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN",
    "forks_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/forks",
    "keys_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/teams",
    "hooks_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/hooks",
    "issue_events_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/issues/events{/number}",
    "events_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/events",
    "assignees_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/assignees{/user}",
    "branches_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/branches{/branch}",
    "tags_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/tags",
    "blobs_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/languages",
    "stargazers_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/stargazers",
    "contributors_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/contributors",
    "subscribers_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/subscribers",
    "subscription_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/subscription",
    "commits_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/contents/{+path}",
    "compare_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/merges",
    "archive_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/downloads",
    "issues_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/issues{/number}",
    "pulls_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/labels{/name}",
    "releases_url": "https://api.github.com/repos/skyline75489/what-happens-when-zh_CN/releases{/id}",
    "created_at": "2015-01-18T23:28:10Z",
    "updated_at": "2015-06-05T09:37:38Z",
    "pushed_at": "2015-06-03T07:36:35Z",
    "git_url": "git://github.com/skyline75489/what-happens-when-zh_CN.git",
    "ssh_url": "git@github.com:skyline75489/what-happens-when-zh_CN.git",
    "clone_url": "https://github.com/skyline75489/what-happens-when-zh_CN.git",
    "svn_url": "https://github.com/skyline75489/what-happens-when-zh_CN",
    "homepage": null,
    "size": 386,
    "stargazers_count": 514,
    "watchers_count": 514,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 82,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 82,
    "open_issues": 0,
    "watchers": 514,
    "default_branch": "master"
  },
  {
    "id": 36694053,
    "name": "pythondirector",
    "full_name": "skyline75489/pythondirector",
    "owner": {
      "login": "skyline75489",
      "id": 4710575,
      "avatar_url": "https://avatars.githubusercontent.com/u/4710575?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skyline75489",
      "html_url": "https://github.com/skyline75489",
      "followers_url": "https://api.github.com/users/skyline75489/followers",
      "following_url": "https://api.github.com/users/skyline75489/following{/other_user}",
      "gists_url": "https://api.github.com/users/skyline75489/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skyline75489/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skyline75489/subscriptions",
      "organizations_url": "https://api.github.com/users/skyline75489/orgs",
      "repos_url": "https://api.github.com/users/skyline75489/repos",
      "events_url": "https://api.github.com/users/skyline75489/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skyline75489/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/skyline75489/pythondirector",
    "description": "Unofficial mirror of pythondirector http://pythondirector.sourceforge.net/",
    "fork": false,
    "url": "https://api.github.com/repos/skyline75489/pythondirector",
    "forks_url": "https://api.github.com/repos/skyline75489/pythondirector/forks",
    "keys_url": "https://api.github.com/repos/skyline75489/pythondirector/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/skyline75489/pythondirector/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/skyline75489/pythondirector/teams",
    "hooks_url": "https://api.github.com/repos/skyline75489/pythondirector/hooks",
    "issue_events_url": "https://api.github.com/repos/skyline75489/pythondirector/issues/events{/number}",
    "events_url": "https://api.github.com/repos/skyline75489/pythondirector/events",
    "assignees_url": "https://api.github.com/repos/skyline75489/pythondirector/assignees{/user}",
    "branches_url": "https://api.github.com/repos/skyline75489/pythondirector/branches{/branch}",
    "tags_url": "https://api.github.com/repos/skyline75489/pythondirector/tags",
    "blobs_url": "https://api.github.com/repos/skyline75489/pythondirector/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/skyline75489/pythondirector/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/skyline75489/pythondirector/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/skyline75489/pythondirector/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/skyline75489/pythondirector/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/skyline75489/pythondirector/languages",
    "stargazers_url": "https://api.github.com/repos/skyline75489/pythondirector/stargazers",
    "contributors_url": "https://api.github.com/repos/skyline75489/pythondirector/contributors",
    "subscribers_url": "https://api.github.com/repos/skyline75489/pythondirector/subscribers",
    "subscription_url": "https://api.github.com/repos/skyline75489/pythondirector/subscription",
    "commits_url": "https://api.github.com/repos/skyline75489/pythondirector/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/skyline75489/pythondirector/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/skyline75489/pythondirector/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/skyline75489/pythondirector/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/skyline75489/pythondirector/contents/{+path}",
    "compare_url": "https://api.github.com/repos/skyline75489/pythondirector/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/skyline75489/pythondirector/merges",
    "archive_url": "https://api.github.com/repos/skyline75489/pythondirector/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/skyline75489/pythondirector/downloads",
    "issues_url": "https://api.github.com/repos/skyline75489/pythondirector/issues{/number}",
    "pulls_url": "https://api.github.com/repos/skyline75489/pythondirector/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/skyline75489/pythondirector/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/skyline75489/pythondirector/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/skyline75489/pythondirector/labels{/name}",
    "releases_url": "https://api.github.com/repos/skyline75489/pythondirector/releases{/id}",
    "created_at": "2015-06-01T23:01:11Z",
    "updated_at": "2015-06-01T23:02:11Z",
    "pushed_at": "2015-06-02T02:58:25Z",
    "git_url": "git://github.com/skyline75489/pythondirector.git",
    "ssh_url": "git@github.com:skyline75489/pythondirector.git",
    "clone_url": "https://github.com/skyline75489/pythondirector.git",
    "svn_url": "https://github.com/skyline75489/pythondirector",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Python",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 35932600,
    "name": "the-little-mongodb-book-pdf-epub",
    "full_name": "skyline75489/the-little-mongodb-book-pdf-epub",
    "owner": {
      "login": "skyline75489",
      "id": 4710575,
      "avatar_url": "https://avatars.githubusercontent.com/u/4710575?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skyline75489",
      "html_url": "https://github.com/skyline75489",
      "followers_url": "https://api.github.com/users/skyline75489/followers",
      "following_url": "https://api.github.com/users/skyline75489/following{/other_user}",
      "gists_url": "https://api.github.com/users/skyline75489/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skyline75489/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skyline75489/subscriptions",
      "organizations_url": "https://api.github.com/users/skyline75489/orgs",
      "repos_url": "https://api.github.com/users/skyline75489/repos",
      "events_url": "https://api.github.com/users/skyline75489/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skyline75489/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/skyline75489/the-little-mongodb-book-pdf-epub",
    "description": "The Little Mongodb Book PDF and epub",
    "fork": false,
    "url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub",
    "forks_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/forks",
    "keys_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/teams",
    "hooks_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/hooks",
    "issue_events_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/issues/events{/number}",
    "events_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/events",
    "assignees_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/assignees{/user}",
    "branches_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/branches{/branch}",
    "tags_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/tags",
    "blobs_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/languages",
    "stargazers_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/stargazers",
    "contributors_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/contributors",
    "subscribers_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/subscribers",
    "subscription_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/subscription",
    "commits_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/contents/{+path}",
    "compare_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/merges",
    "archive_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/downloads",
    "issues_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/issues{/number}",
    "pulls_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/labels{/name}",
    "releases_url": "https://api.github.com/repos/skyline75489/the-little-mongodb-book-pdf-epub/releases{/id}",
    "created_at": "2015-05-20T07:22:41Z",
    "updated_at": "2015-05-23T14:09:54Z",
    "pushed_at": "2015-05-20T08:00:07Z",
    "git_url": "git://github.com/skyline75489/the-little-mongodb-book-pdf-epub.git",
    "ssh_url": "git@github.com:skyline75489/the-little-mongodb-book-pdf-epub.git",
    "clone_url": "https://github.com/skyline75489/the-little-mongodb-book-pdf-epub.git",
    "svn_url": "https://github.com/skyline75489/the-little-mongodb-book-pdf-epub",
    "homepage": null,
    "size": 376,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master"
  }
];



module.exports = React.createClass({
  getInitialState: function() {
    var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
    return {
      dataSource: ds.cloneWithRows(this.props.dataSource),
    };
  },
  _renderRow: function(data) {
    return (
      <View style={styles.row}>
         <RepoRow data={data} goToRepo={this.props.goToRepo}/>
      </View>
    );
  },
  render: function() {
    return(
      <ListView 
      dataSource={this.state.dataSource}
      renderRow={this._renderRow}
      scrollEnabled={this.props.scrollEnabled}>
      </ListView>
    );
  },
});

var styles = StyleSheet.create({
  row: {
    flex: 1,
    paddingLeft: 20,
    paddingTop: 10,
    paddingBottom: 10,
    overflow: 'hidden',
    borderBottomWidth: 0.5,
    borderColor: '#F1F1F1',
  },
});

