'use strict';

var React = require('react-native');

var {
  ListView,
  StyleSheet,
  View,
  Text,
  Image,
  TouchableHighlight,
  TouchableOpacity,
  StatusBarIOS
} = React;

var RepoRow = require('./RepoRow');

var FAKE_DATA = [
  {
    "id": 29015704,
    "name": "Annie",
    "full_name": "skyline75489/Annie",
    "owner": {
      "login": "skyline75489",
      "id": 4710575,
      "avatar_url": "https://avatars.githubusercontent.com/u/4710575?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skyline75489",
      "html_url": "https://github.com/skyline75489",
      "followers_url": "https://api.github.com/users/skyline75489/followers",
      "following_url": "https://api.github.com/users/skyline75489/following{/other_user}",
      "gists_url": "https://api.github.com/users/skyline75489/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skyline75489/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skyline75489/subscriptions",
      "organizations_url": "https://api.github.com/users/skyline75489/orgs",
      "repos_url": "https://api.github.com/users/skyline75489/repos",
      "events_url": "https://api.github.com/users/skyline75489/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skyline75489/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/skyline75489/Annie",
    "description": "A sample Markdown parser written in Swift",
    "fork": false,
    "url": "https://api.github.com/repos/skyline75489/Annie",
    "forks_url": "https://api.github.com/repos/skyline75489/Annie/forks",
    "keys_url": "https://api.github.com/repos/skyline75489/Annie/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/skyline75489/Annie/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/skyline75489/Annie/teams",
    "hooks_url": "https://api.github.com/repos/skyline75489/Annie/hooks",
    "issue_events_url": "https://api.github.com/repos/skyline75489/Annie/issues/events{/number}",
    "events_url": "https://api.github.com/repos/skyline75489/Annie/events",
    "assignees_url": "https://api.github.com/repos/skyline75489/Annie/assignees{/user}",
    "branches_url": "https://api.github.com/repos/skyline75489/Annie/branches{/branch}",
    "tags_url": "https://api.github.com/repos/skyline75489/Annie/tags",
    "blobs_url": "https://api.github.com/repos/skyline75489/Annie/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/skyline75489/Annie/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/skyline75489/Annie/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/skyline75489/Annie/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/skyline75489/Annie/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/skyline75489/Annie/languages",
    "stargazers_url": "https://api.github.com/repos/skyline75489/Annie/stargazers",
    "contributors_url": "https://api.github.com/repos/skyline75489/Annie/contributors",
    "subscribers_url": "https://api.github.com/repos/skyline75489/Annie/subscribers",
    "subscription_url": "https://api.github.com/repos/skyline75489/Annie/subscription",
    "commits_url": "https://api.github.com/repos/skyline75489/Annie/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/skyline75489/Annie/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/skyline75489/Annie/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/skyline75489/Annie/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/skyline75489/Annie/contents/{+path}",
    "compare_url": "https://api.github.com/repos/skyline75489/Annie/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/skyline75489/Annie/merges",
    "archive_url": "https://api.github.com/repos/skyline75489/Annie/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/skyline75489/Annie/downloads",
    "issues_url": "https://api.github.com/repos/skyline75489/Annie/issues{/number}",
    "pulls_url": "https://api.github.com/repos/skyline75489/Annie/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/skyline75489/Annie/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/skyline75489/Annie/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/skyline75489/Annie/labels{/name}",
    "releases_url": "https://api.github.com/repos/skyline75489/Annie/releases{/id}",
    "created_at": "2015-01-09T12:33:08Z",
    "updated_at": "2015-01-13T01:16:13Z",
    "pushed_at": "2015-01-13T01:16:13Z",
    "git_url": "git://github.com/skyline75489/Annie.git",
    "ssh_url": "git@github.com:skyline75489/Annie.git",
    "clone_url": "https://github.com/skyline75489/Annie.git",
    "svn_url": "https://github.com/skyline75489/Annie",
    "homepage": null,
    "size": 164,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Swift",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22777926,
    "name": "awesome-python",
    "full_name": "skyline75489/awesome-python",
    "owner": {
      "login": "skyline75489",
      "id": 4710575,
      "avatar_url": "https://avatars.githubusercontent.com/u/4710575?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skyline75489",
      "html_url": "https://github.com/skyline75489",
      "followers_url": "https://api.github.com/users/skyline75489/followers",
      "following_url": "https://api.github.com/users/skyline75489/following{/other_user}",
      "gists_url": "https://api.github.com/users/skyline75489/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skyline75489/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skyline75489/subscriptions",
      "organizations_url": "https://api.github.com/users/skyline75489/orgs",
      "repos_url": "https://api.github.com/users/skyline75489/repos",
      "events_url": "https://api.github.com/users/skyline75489/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skyline75489/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/skyline75489/awesome-python",
    "description": "A curated list of awesome Python frameworks, libraries and software.",
    "fork": true,
    "url": "https://api.github.com/repos/skyline75489/awesome-python",
    "forks_url": "https://api.github.com/repos/skyline75489/awesome-python/forks",
    "keys_url": "https://api.github.com/repos/skyline75489/awesome-python/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/skyline75489/awesome-python/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/skyline75489/awesome-python/teams",
    "hooks_url": "https://api.github.com/repos/skyline75489/awesome-python/hooks",
    "issue_events_url": "https://api.github.com/repos/skyline75489/awesome-python/issues/events{/number}",
    "events_url": "https://api.github.com/repos/skyline75489/awesome-python/events",
    "assignees_url": "https://api.github.com/repos/skyline75489/awesome-python/assignees{/user}",
    "branches_url": "https://api.github.com/repos/skyline75489/awesome-python/branches{/branch}",
    "tags_url": "https://api.github.com/repos/skyline75489/awesome-python/tags",
    "blobs_url": "https://api.github.com/repos/skyline75489/awesome-python/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/skyline75489/awesome-python/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/skyline75489/awesome-python/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/skyline75489/awesome-python/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/skyline75489/awesome-python/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/skyline75489/awesome-python/languages",
    "stargazers_url": "https://api.github.com/repos/skyline75489/awesome-python/stargazers",
    "contributors_url": "https://api.github.com/repos/skyline75489/awesome-python/contributors",
    "subscribers_url": "https://api.github.com/repos/skyline75489/awesome-python/subscribers",
    "subscription_url": "https://api.github.com/repos/skyline75489/awesome-python/subscription",
    "commits_url": "https://api.github.com/repos/skyline75489/awesome-python/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/skyline75489/awesome-python/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/skyline75489/awesome-python/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/skyline75489/awesome-python/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/skyline75489/awesome-python/contents/{+path}",
    "compare_url": "https://api.github.com/repos/skyline75489/awesome-python/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/skyline75489/awesome-python/merges",
    "archive_url": "https://api.github.com/repos/skyline75489/awesome-python/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/skyline75489/awesome-python/downloads",
    "issues_url": "https://api.github.com/repos/skyline75489/awesome-python/issues{/number}",
    "pulls_url": "https://api.github.com/repos/skyline75489/awesome-python/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/skyline75489/awesome-python/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/skyline75489/awesome-python/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/skyline75489/awesome-python/labels{/name}",
    "releases_url": "https://api.github.com/repos/skyline75489/awesome-python/releases{/id}",
    "created_at": "2014-08-09T03:24:53Z",
    "updated_at": "2014-08-09T03:30:20Z",
    "pushed_at": "2014-08-09T03:30:20Z",
    "git_url": "git://github.com/skyline75489/awesome-python.git",
    "ssh_url": "git@github.com:skyline75489/awesome-python.git",
    "clone_url": "https://github.com/skyline75489/awesome-python.git",
    "svn_url": "https://github.com/skyline75489/awesome-python",
    "homepage": "",
    "size": 1801,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 20616929,
    "name": "baidu-tieba-auto-sign",
    "full_name": "skyline75489/baidu-tieba-auto-sign",
    "owner": {
      "login": "skyline75489",
      "id": 4710575,
      "avatar_url": "https://avatars.githubusercontent.com/u/4710575?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skyline75489",
      "html_url": "https://github.com/skyline75489",
      "followers_url": "https://api.github.com/users/skyline75489/followers",
      "following_url": "https://api.github.com/users/skyline75489/following{/other_user}",
      "gists_url": "https://api.github.com/users/skyline75489/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skyline75489/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skyline75489/subscriptions",
      "organizations_url": "https://api.github.com/users/skyline75489/orgs",
      "repos_url": "https://api.github.com/users/skyline75489/repos",
      "events_url": "https://api.github.com/users/skyline75489/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skyline75489/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/skyline75489/baidu-tieba-auto-sign",
    "description": "模拟客户端进行百度贴吧批量签到的Python脚本",
    "fork": false,
    "url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign",
    "forks_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/forks",
    "keys_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/teams",
    "hooks_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/hooks",
    "issue_events_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/issues/events{/number}",
    "events_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/events",
    "assignees_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/assignees{/user}",
    "branches_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/branches{/branch}",
    "tags_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/tags",
    "blobs_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/languages",
    "stargazers_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/stargazers",
    "contributors_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/contributors",
    "subscribers_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/subscribers",
    "subscription_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/subscription",
    "commits_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/contents/{+path}",
    "compare_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/merges",
    "archive_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/downloads",
    "issues_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/issues{/number}",
    "pulls_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/labels{/name}",
    "releases_url": "https://api.github.com/repos/skyline75489/baidu-tieba-auto-sign/releases{/id}",
    "created_at": "2014-06-08T13:12:44Z",
    "updated_at": "2015-05-19T00:56:26Z",
    "pushed_at": "2015-03-15T09:36:05Z",
    "git_url": "git://github.com/skyline75489/baidu-tieba-auto-sign.git",
    "ssh_url": "git@github.com:skyline75489/baidu-tieba-auto-sign.git",
    "clone_url": "https://github.com/skyline75489/baidu-tieba-auto-sign.git",
    "svn_url": "https://github.com/skyline75489/baidu-tieba-auto-sign",
    "homepage": null,
    "size": 256,
    "stargazers_count": 24,
    "watchers_count": 24,
    "language": "Python",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 27,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 27,
    "open_issues": 0,
    "watchers": 24,
    "default_branch": "master"
  },
  {
    "id": 31364707,
    "name": "bebusy.py",
    "full_name": "skyline75489/bebusy.py",
    "owner": {
      "login": "skyline75489",
      "id": 4710575,
      "avatar_url": "https://avatars.githubusercontent.com/u/4710575?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skyline75489",
      "html_url": "https://github.com/skyline75489",
      "followers_url": "https://api.github.com/users/skyline75489/followers",
      "following_url": "https://api.github.com/users/skyline75489/following{/other_user}",
      "gists_url": "https://api.github.com/users/skyline75489/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skyline75489/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skyline75489/subscriptions",
      "organizations_url": "https://api.github.com/users/skyline75489/orgs",
      "repos_url": "https://api.github.com/users/skyline75489/repos",
      "events_url": "https://api.github.com/users/skyline75489/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skyline75489/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/skyline75489/bebusy.py",
    "description": "Python Terminal  log generator for work spoofing (inspired by https://github.com/ondrek/bebusy.js)",
    "fork": false,
    "url": "https://api.github.com/repos/skyline75489/bebusy.py",
    "forks_url": "https://api.github.com/repos/skyline75489/bebusy.py/forks",
    "keys_url": "https://api.github.com/repos/skyline75489/bebusy.py/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/skyline75489/bebusy.py/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/skyline75489/bebusy.py/teams",
    "hooks_url": "https://api.github.com/repos/skyline75489/bebusy.py/hooks",
    "issue_events_url": "https://api.github.com/repos/skyline75489/bebusy.py/issues/events{/number}",
    "events_url": "https://api.github.com/repos/skyline75489/bebusy.py/events",
    "assignees_url": "https://api.github.com/repos/skyline75489/bebusy.py/assignees{/user}",
    "branches_url": "https://api.github.com/repos/skyline75489/bebusy.py/branches{/branch}",
    "tags_url": "https://api.github.com/repos/skyline75489/bebusy.py/tags",
    "blobs_url": "https://api.github.com/repos/skyline75489/bebusy.py/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/skyline75489/bebusy.py/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/skyline75489/bebusy.py/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/skyline75489/bebusy.py/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/skyline75489/bebusy.py/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/skyline75489/bebusy.py/languages",
    "stargazers_url": "https://api.github.com/repos/skyline75489/bebusy.py/stargazers",
    "contributors_url": "https://api.github.com/repos/skyline75489/bebusy.py/contributors",
    "subscribers_url": "https://api.github.com/repos/skyline75489/bebusy.py/subscribers",
    "subscription_url": "https://api.github.com/repos/skyline75489/bebusy.py/subscription",
    "commits_url": "https://api.github.com/repos/skyline75489/bebusy.py/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/skyline75489/bebusy.py/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/skyline75489/bebusy.py/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/skyline75489/bebusy.py/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/skyline75489/bebusy.py/contents/{+path}",
    "compare_url": "https://api.github.com/repos/skyline75489/bebusy.py/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/skyline75489/bebusy.py/merges",
    "archive_url": "https://api.github.com/repos/skyline75489/bebusy.py/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/skyline75489/bebusy.py/downloads",
    "issues_url": "https://api.github.com/repos/skyline75489/bebusy.py/issues{/number}",
    "pulls_url": "https://api.github.com/repos/skyline75489/bebusy.py/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/skyline75489/bebusy.py/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/skyline75489/bebusy.py/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/skyline75489/bebusy.py/labels{/name}",
    "releases_url": "https://api.github.com/repos/skyline75489/bebusy.py/releases{/id}",
    "created_at": "2015-02-26T11:50:47Z",
    "updated_at": "2015-04-13T13:24:10Z",
    "pushed_at": "2015-05-09T01:38:36Z",
    "git_url": "git://github.com/skyline75489/bebusy.py.git",
    "ssh_url": "git@github.com:skyline75489/bebusy.py.git",
    "clone_url": "https://github.com/skyline75489/bebusy.py.git",
    "svn_url": "https://github.com/skyline75489/bebusy.py",
    "homepage": null,
    "size": 4143,
    "stargazers_count": 9,
    "watchers_count": 9,
    "language": "Python",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 2,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 2,
    "open_issues": 0,
    "watchers": 9,
    "default_branch": "master"
  },
  {
    "id": 32974150,
    "name": "DES",
    "full_name": "skyline75489/DES",
    "owner": {
      "login": "skyline75489",
      "id": 4710575,
      "avatar_url": "https://avatars.githubusercontent.com/u/4710575?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skyline75489",
      "html_url": "https://github.com/skyline75489",
      "followers_url": "https://api.github.com/users/skyline75489/followers",
      "following_url": "https://api.github.com/users/skyline75489/following{/other_user}",
      "gists_url": "https://api.github.com/users/skyline75489/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skyline75489/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skyline75489/subscriptions",
      "organizations_url": "https://api.github.com/users/skyline75489/orgs",
      "repos_url": "https://api.github.com/users/skyline75489/repos",
      "events_url": "https://api.github.com/users/skyline75489/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skyline75489/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/skyline75489/DES",
    "description": "Encryption and decryption using DES",
    "fork": true,
    "url": "https://api.github.com/repos/skyline75489/DES",
    "forks_url": "https://api.github.com/repos/skyline75489/DES/forks",
    "keys_url": "https://api.github.com/repos/skyline75489/DES/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/skyline75489/DES/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/skyline75489/DES/teams",
    "hooks_url": "https://api.github.com/repos/skyline75489/DES/hooks",
    "issue_events_url": "https://api.github.com/repos/skyline75489/DES/issues/events{/number}",
    "events_url": "https://api.github.com/repos/skyline75489/DES/events",
    "assignees_url": "https://api.github.com/repos/skyline75489/DES/assignees{/user}",
    "branches_url": "https://api.github.com/repos/skyline75489/DES/branches{/branch}",
    "tags_url": "https://api.github.com/repos/skyline75489/DES/tags",
    "blobs_url": "https://api.github.com/repos/skyline75489/DES/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/skyline75489/DES/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/skyline75489/DES/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/skyline75489/DES/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/skyline75489/DES/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/skyline75489/DES/languages",
    "stargazers_url": "https://api.github.com/repos/skyline75489/DES/stargazers",
    "contributors_url": "https://api.github.com/repos/skyline75489/DES/contributors",
    "subscribers_url": "https://api.github.com/repos/skyline75489/DES/subscribers",
    "subscription_url": "https://api.github.com/repos/skyline75489/DES/subscription",
    "commits_url": "https://api.github.com/repos/skyline75489/DES/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/skyline75489/DES/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/skyline75489/DES/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/skyline75489/DES/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/skyline75489/DES/contents/{+path}",
    "compare_url": "https://api.github.com/repos/skyline75489/DES/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/skyline75489/DES/merges",
    "archive_url": "https://api.github.com/repos/skyline75489/DES/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/skyline75489/DES/downloads",
    "issues_url": "https://api.github.com/repos/skyline75489/DES/issues{/number}",
    "pulls_url": "https://api.github.com/repos/skyline75489/DES/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/skyline75489/DES/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/skyline75489/DES/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/skyline75489/DES/labels{/name}",
    "releases_url": "https://api.github.com/repos/skyline75489/DES/releases{/id}",
    "created_at": "2015-03-27T07:56:13Z",
    "updated_at": "2015-03-29T03:57:37Z",
    "pushed_at": "2015-03-29T03:57:35Z",
    "git_url": "git://github.com/skyline75489/DES.git",
    "ssh_url": "git@github.com:skyline75489/DES.git",
    "clone_url": "https://github.com/skyline75489/DES.git",
    "svn_url": "https://github.com/skyline75489/DES",
    "homepage": null,
    "size": 95,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "Python",
    "has_issues": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 1,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 1,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master"
  },
  {
    "id": 32726530,
    "name": "dg",
    "full_name": "skyline75489/dg",
    "owner": {
      "login": "skyline75489",
      "id": 4710575,
      "avatar_url": "https://avatars.githubusercontent.com/u/4710575?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skyline75489",
      "html_url": "https://github.com/skyline75489",
      "followers_url": "https://api.github.com/users/skyline75489/followers",
      "following_url": "https://api.github.com/users/skyline75489/following{/other_user}",
      "gists_url": "https://api.github.com/users/skyline75489/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skyline75489/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skyline75489/subscriptions",
      "organizations_url": "https://api.github.com/users/skyline75489/orgs",
      "repos_url": "https://api.github.com/users/skyline75489/repos",
      "events_url": "https://api.github.com/users/skyline75489/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skyline75489/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/skyline75489/dg",
    "description": "A directory generator",
    "fork": false,
    "url": "https://api.github.com/repos/skyline75489/dg",
    "forks_url": "https://api.github.com/repos/skyline75489/dg/forks",
    "keys_url": "https://api.github.com/repos/skyline75489/dg/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/skyline75489/dg/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/skyline75489/dg/teams",
    "hooks_url": "https://api.github.com/repos/skyline75489/dg/hooks",
    "issue_events_url": "https://api.github.com/repos/skyline75489/dg/issues/events{/number}",
    "events_url": "https://api.github.com/repos/skyline75489/dg/events",
    "assignees_url": "https://api.github.com/repos/skyline75489/dg/assignees{/user}",
    "branches_url": "https://api.github.com/repos/skyline75489/dg/branches{/branch}",
    "tags_url": "https://api.github.com/repos/skyline75489/dg/tags",
    "blobs_url": "https://api.github.com/repos/skyline75489/dg/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/skyline75489/dg/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/skyline75489/dg/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/skyline75489/dg/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/skyline75489/dg/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/skyline75489/dg/languages",
    "stargazers_url": "https://api.github.com/repos/skyline75489/dg/stargazers",
    "contributors_url": "https://api.github.com/repos/skyline75489/dg/contributors",
    "subscribers_url": "https://api.github.com/repos/skyline75489/dg/subscribers",
    "subscription_url": "https://api.github.com/repos/skyline75489/dg/subscription",
    "commits_url": "https://api.github.com/repos/skyline75489/dg/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/skyline75489/dg/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/skyline75489/dg/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/skyline75489/dg/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/skyline75489/dg/contents/{+path}",
    "compare_url": "https://api.github.com/repos/skyline75489/dg/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/skyline75489/dg/merges",
    "archive_url": "https://api.github.com/repos/skyline75489/dg/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/skyline75489/dg/downloads",
    "issues_url": "https://api.github.com/repos/skyline75489/dg/issues{/number}",
    "pulls_url": "https://api.github.com/repos/skyline75489/dg/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/skyline75489/dg/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/skyline75489/dg/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/skyline75489/dg/labels{/name}",
    "releases_url": "https://api.github.com/repos/skyline75489/dg/releases{/id}",
    "created_at": "2015-03-23T10:53:24Z",
    "updated_at": "2015-03-24T00:29:32Z",
    "pushed_at": "2015-03-24T00:29:32Z",
    "git_url": "git://github.com/skyline75489/dg.git",
    "ssh_url": "git@github.com:skyline75489/dg.git",
    "clone_url": "https://github.com/skyline75489/dg.git",
    "svn_url": "https://github.com/skyline75489/dg",
    "homepage": null,
    "size": 140,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "Python",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master"
  },
];


module.exports = React.createClass({
  getInitialState: function() {
    var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
    return {
      dataSource: ds.cloneWithRows(FAKE_DATA),
    };
  },
  _renderRow: function(data) {
    return (
      <View style={styles.row}>
         <RepoRow data={data}/>
      </View>
    );
  },
  render: function() {
    return(
      <ListView 
      dataSource={this.state.dataSource}
      renderRow={this._renderRow}
      noScroll={this.props.noScroll}>
      </ListView>
    );
  },
});

var styles = StyleSheet.create({
  row: {
    flex: 1,
    paddingLeft: 20,
    paddingTop: 5,
    paddingBottom: 10,
    overflow: 'hidden',
    borderBottomWidth: 0.5,
    borderColor: '#F1F1F1',
  },
});

